import mongoose, { Schema } from "mongoose";

const AppSchema = new Schema({
  name: String,
  label: String,
  author_id: String,
  version: Number,
  version_full: String,
  theme: String,
  base: Schema.Types.Mixed,
  common_data: Schema.Types.Mixed,
  opensource: Boolean,
  public: Boolean,
  language: String,
  approved: Boolean,
  countries: String,
  global: String,
  website: String,
  created: String,
  compiled_name: String,
  docs: String,
  icon_128: Schema.Types.Mixed,
  icon_256: Schema.Types.Mixed,
  icon_32: Schema.Types.Mixed,
  icon_512: Schema.Types.Mixed,
  icon_64: Schema.Types.Mixed,
  approved_at: String,
  in_review: Boolean,
  keywords: Schema.Types.Mixed,
  manifest_version: Number,
  invite_token: String,
  groups: [Schema.Types.Mixed],
  install_spec: [Schema.Types.Mixed],
  install: Schema.Types.Mixed,
  icon_color_512: Schema.Types.Mixed,
  icon_color_256: Schema.Types.Mixed,
  icon_color_128: Schema.Types.Mixed,
  icon_color_64: Schema.Types.Mixed,
  icon_color_32: Schema.Types.Mixed,
  description: String,
  beta: Boolean,
  billable: Boolean,
  categories: Schema.Types.Mixed,
  origin: String,
  rev: Number,
  ipm_repo: String,
  flags: Schema.Types.Mixed,
  ipm_tags: String,
});

export const AppModel = mongoose.model("App", AppSchema);
